### PR TITLE
As a user, I want to be able to set a default string, so that a predefined message can be used

### PR DESCRIPTION
**Pull request by zephimir**
Small PR to allow users to be able to set default strings for variables. This also contains a bug fix.
Also, there was a missing space in the default options in constants

WHO
As a user, 

WHAT
I want to be able to set a default string for a variable

WHY ?
* To be able to have predefined messages if I so desire
* To fix a bug because today if a string is put insteadf of an array, the if condition triggers as an array and will therefore crash the message

### CODE REVIEW

**Comment by zephimir** [comment]
Hello @rioukkevin  I wanted to say thank you for the amazing job on this extension. I think my team will find it usefull. I found a usecase that I would like to add. I hope you will find this interesting :)

**Comment by rioukkevin** [comment]
Hi @zephimir 

That's a good idea, thanks for making a PR, I look for the code and test it in next days 😉 

Have a nice day
Kevin

**Comment by zephimir** [comment]
Hey @rioukkevin ! Have you had the time to take a quick look at it? :)

**Comment by rioukkevin** [comment]
Hi @zephimir I have time to look to the code, it looks good, I only need to test it for PR approval, I'm sorry I'm busy, I test it ASAP 😉 
Sorry for delay

**Comment by rioukkevin** [comment]
I test it now ;)

**Comment by rioukkevin** [comment]
I test it and it suppress the functionnality of predefinedTemplates like alpha8 or keke, so, I work on code to add a new setting named `vscodeGitCommit.defaultVariablesValue` looking like:
```json
"vscodeGitCommit.defaultVariablesValue": {
  "<variable_name>":"defaultValue",
  // ...
}
```
that permit to define default value for any variables not defined in variables :wink:

I think I can finish it tomorrow 

BTW: I'm adding other feature request to it and publish the 3.0.2 version

**Comment by rioukkevin** [comment]
I close the PR cause I publish a new version v3.0.2 with the feature in an other setting 😉

**Pull request closed without merging**
